services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - 8000:80
      - 9000:443
    env_file:
      - .env
    volumes:
      - ./static:/static
      - ./cache:/cache
      - /etc/letsencrypt:/cert
      - ./db:/db
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
